<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Grade Verification Slip Generations table.
 *
 * Tracks every slip generated by an applicant:
 * - Who generated it (user_id)
 * - The stored PDF file (filename, file_path)
 * - Reference number snapshot for quick lookup
 * - How many times it has been downloaded
 * - First generated at / last downloaded at
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('gvs_generations', function (Blueprint $table) {
            $table->id();

            // The applicant who generated the slip
            $table->unsignedBigInteger('user_id')->index();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');

            // Snapshot of the reference number at generation time
            $table->string('reference_number')->nullable()->index();

            // Stored PDF
            $table->string('filename');
            $table->string('file_path');

            // Download tracking
            $table->unsignedInteger('download_count')->default(1);
            $table->timestamp('last_downloaded_at')->nullable();

            $table->timestamps(); // created_at = first generated
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('gvs_generations');
    }
};
